spring.application.name=JobPortal
spring.datasource.url=jdbc:mysql://localhost:3306/job_portal2
spring.datasource.username=root
spring.datasource.password=Oct31#vipul
logging.level.org.springframework.security=DEBUG
spring.jpa.hibernate.ddl-auto=update

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=vipul23600@iiitd.ac.in
spring.mail.password=ezcyybfsatrncydk
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true