spring.application.name=JobPortal
spring.datasource.url=jdbc:mysql://localhost:3306/job_portal2
spring.datasource.username=root
spring.datasource.password=Oct31#vipul
logging.level.org.springframework.security=DEBUG